name: clang-format

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    # https://apt.llvm.org/
    - name: Install clang-format-19
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main'
        sudo add-apt-repository 'deb-src http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main'
        sudo apt-get update
        sudo apt-get install -y clang-format-19

    - name: Check formatting
      run: find . -name "*.hpp" -o -name "*.cpp" -not -iwholename "*/.verify-helper/*" | xargs clang-format-19 --dry-run --Werror -style=file
